dependencies:
- name: prometheus
  version: 6.8.1
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: grafana
#  version: 1.12.0
  version: 2.0.2
  repository: https://kubernetes-charts.storage.googleapis.com/

